### ISSUE TITLE
Why didn't you synchronize the new version of the SDK

### ISSUE THREAD

**Issue by cgrrty** [Consti10/rv1126#10]
The new version of SDK should be 1.8.X. You are using 1.6.X now.

**Comment by Consti10** [comment]
I'm still on 1.6x because for the stuff i'm working on 1.6x is sueficient and switching it requires some carefull considerations, too. I might just entirely switch to 1.8 soon though.

**Comment by Consti10** [comment]
at last when i have the A201 dev board
